[package]
name = "gemi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.gemi-core]
path = "../../lib/core"

[dependencies.gemi-utils]
path = "../../lib/utils"

[dependencies.sdl2]
version = "0.36.0"
features = ["bundled", "static-link", "unsafe_textures"]
